"""Build the operator's paced companion without credentials or participant data."""
from pathlib import Path
import html,json,re
root=Path(__file__).resolve().parents[1]
slides=json.loads(re.search(r'window.SLIDES\s*=\s*(\[.*?\]);',(root/'deck/index.html').read_text(),re.S)[1])
nums={s['id']:s['num'] for s in slides}
blocks=[
(0,6,'Why personal agents','s2','Slides', 'Introduce Muse, Instinct, Dots, OpenClaw and Hermes. Ask what work the room would delegate to an agent.', 'An agent needs a place to run, a wallet, a budget and a way to prove what happened.', 'The room has one concrete agent job in mind.', 'Keep the opening to six minutes; skip extra examples.'),
(6,11,'Why AEX','s5','Slides + architecture drill-downs','Show the market, runtime, inference and security plane. Walk discover → agree → escrow → run → settle.', 'AEX brings the agent, its compute and its spending authority together.', 'Keep architecture claims separate from today’s installed standalone recipe.', 'Use the architecture diagram; AEX self-deployment is not required for this route.'),
(11,16,'Authority and budget','s9','Slides','Explain ownership, limits and the four budgets: AEX, WaaP, transaction gas and position capital.', 'The local build has no AEX deployment fee. A proposal, a simulation and a confirmed transaction are different results.', 'No one interprets a funding registration receipt as a payment or an unsigned simulation as a swap.', 'Do not promise an allowance until the complete funded recipe has been measured.'),
(16,20,'Tour one agent','s13','Deck → runtime console','Show the seven controls. Explain where each action runs: local computer for builders; Studio through the tunnel for this presenter.', 'Check the runtime. Set up a wallet. Save the strategy. Install the agent. Run and inspect it. Change a rule, then stop.', 'The audience understands the sequence before downloading.', 'Keep Guardian as a later recipe. Finish one working Rebalancer first.'),
(20,25,'Build QR and wallet setup','s14','Build QR → deployment guide → console','Show Build QR and the full URL. Builders install Node 24, unzip the kit and run PORT=8788 node server.mjs --open (or PORT=8789 for the separate local rehearsal). Step 01 checks Node; step 02 runs node wallet-setup.mjs in a second terminal. They create or sign in, approve email, copy the Sui address into Strategy, and save.', 'Use your own email and wallet. Once saved, the Funding panel includes that wallet address automatically.', 'Wallet setup prints an email and full Sui address. Strategy contains that same address. No historical example is used for funding.', 'Pair with a laptop that is ready. Choose port 8789 below for a separate local rehearsal, or 8788 to reuse the existing console. Keep the selected port and launch command matched. Node 26 is not the tested runtime.'),
(25,34,'Register, install and run together','s15','Funding QR → operator → runtime console','When wallets are ready, select Funding QR. Registration accepts submissions without starting a timer. Optionally start a 15-minute reminder on the private operator screen. Builders enter email in Funding; direct QR users enter email and address. Use the numbered console links below. Open 03 Install agent and click Install dependencies. Wait until Dependencies reads Installed. Open 04 Start / run and click Run once. Read the new output before proceeding.', 'The install button runs npm ci. Installation does not start the agent. One run reads actual wallet balances and the live Sui pool.', 'Show installation events, then a fresh checkpoint, price, balances and outcome from the funded presenter wallet.', 'If funding is not ready, explain the actual balance block. Continue installation while funding is processed; do not present historical results as a new run.'),
(34,40,'Change one strategy rule','s18','Runtime Modify → Run → Inspect','With a rehearsed funded configuration, change one threshold and run again. Compare HOLD against a proposed action. Inspect quote, unsigned build and Sui simulation separately.', 'The rule changed. Now compare the inputs and explain why the result changed.', 'Each output is timestamped and has the current configured wallet. A simulation is explicitly labelled.', 'If price or holdings do not meet the rule, explain HOLD. Do not invent a trade. A signed swap is only shown after its separate funded rehearsal passes.'),
(40,57,'Independent build + funding handoff','s20','Participant consoles + private funding operator','When ready to fund, refresh operator controls and export campaign.json and responses.csv. The first 30 unique registrations are selected in server order; the rest join the waitlist. Pass both to the payout agent with the approved allowance, total, source account and reserve. Review the exact plan before sending. Builders check receipts, run, modify and stop their own agent.', 'Keep one result you can explain: the rule, the live inputs and the output.', 'At most 30 selected recipients; waitlisted builders can continue setup. Every sent payment has its own checked receipt.', 'An unresolved payment stops payout processing. Never create a second ledger to retry. Allowance and source authentication must be ready before live sending.'),
(57,60,'Close','s24','Closing slide','Ask what they will build next. Link the deployment guide and canonical recipe. Confirm the presenter’s monitoring is stopped.', 'Keep the recipe, your configuration and your evidence.', 'Builders know the next step and the session ends on time.', 'No operator checklist or setup appendix in the audience deck.'),
]
runtime='http://127.0.0.1:8788/'
steps={
'prepare':('01 Check runtime','Click Check runtime (or Check runtime again). This verifies Node and recipe files; installation comes at step 03.'),
'configure':('02 Wallet + configure','Select Wallet and follow the setup command. Select Strategy, paste the returned Sui address, then click Save and continue to funding. Funding collects the email for that saved wallet.'),
'deploy':('03 Install agent','Click Install dependencies (or Install dependencies again). Wait for Dependencies: Installed and check the installation output.'),
'run':('04 Start / run','Click Run once. Wait for a fresh timestamp and output. Read the actual outcome, including any funding block; an unsigned simulation is not a submitted swap.'),
'inspect':('05 Inspect','Read the latest output, expand Raw execution output and open its checkpoint or transaction link when available.'),
'modify':('06 Modify','Change one threshold, click Apply configuration, then return to 04 Start / run and click Run once.'),
'stop':('07 Stop','If monitoring is running, click Stop agent. Click Save output to retain the result. A single Run once already exits after its cycle.'),
}
block_steps={16:[],20:['prepare','configure'],25:['deploy','run','inspect'],34:['modify','run','inspect'],40:['run','inspect','stop'],57:['stop']}
def step_links(ids):
    return '<ol class="action-steps">'+''.join(f'<li><a href="{runtime}#{key}" target="rebalancer-runtime">Open {steps[key][0]} ↗</a><p>{html.escape(steps[key][1])}</p></li>' for key in ids)+'</ol>' if ids else ''
sections=[]
for start,end,title,sid,screen,action,say,expected,fallback in blocks:
    controls=f'<a href="index.html#{sid}" target="workshop-deck">Open slide {nums.get(sid,"?")} ↗</a>'
    sections.append(f'<section class="block" id="minute-{start}" data-start="{start}" data-end="{end}"><header><span class="time">{start:02}–{end:02} min</span><h2>{html.escape(title)}</h2>{controls}</header><dl><dt>Screen</dt><dd>{html.escape(screen)}</dd><dt>Do</dt><dd>{html.escape(action)}</dd><dt>Say</dt><dd>{html.escape(say)}</dd><dt>Look for</dt><dd>{html.escape(expected)}</dd><dt>If stuck</dt><dd>{html.escape(fallback)}</dd></dl>{step_links(block_steps.get(start,[]))}<label class="done"><input type="checkbox" data-check="block-{start}"> Complete</label></section>')
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Basecamp · presenter companion</title><style>
:root{color-scheme:dark;font-family:system-ui,sans-serif;background:#0a0a0a;color:#f5f5f5}*{box-sizing:border-box}body{margin:0}a{color:#80b0ff;text-underline-offset:4px}button{font:inherit;cursor:pointer;background:#3458ea;border:0;border-radius:24px;color:white;padding:10px 16px}main{max-width:1180px;margin:auto;padding:28px 24px 80px}h1{font-size:38px;letter-spacing:-.04em;margin:8px 0}h2{font-size:24px;margin:0}p,li,dd{line-height:1.6;color:#c2c2c2}code,pre{font-family:ui-monospace,monospace}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#0a0a0a;padding:16px;border-radius:12px}.toolbar{position:sticky;top:0;z-index:2;background:#141414f5;border-bottom:1px solid #333;padding:16px 24px;display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap}.timer{font:30px ui-monospace,monospace}.controls,.links{display:flex;flex-wrap:wrap;gap:12px}.links{margin:22px 0}.links a{border:1px solid #444;border-radius:24px;padding:10px 16px;text-decoration:none}.block,.preflight{border:1px solid #333;border-radius:16px;background:#141414;padding:24px;margin:20px 0;scroll-margin-top:100px}.block.active{border-color:#3458ea;box-shadow:inset 4px 0 #3458ea}.block header{display:flex;align-items:center;gap:18px;flex-wrap:wrap}.block header a{margin-left:auto}.time{color:#80b0ff;font-weight:600}dl{display:grid;grid-template-columns:90px 1fr;gap:12px 20px;margin-bottom:24px}dt{color:#80b0ff;font-size:13px;padding-top:4px}dd{margin:0}.done{color:#a3a3a3;display:block;padding:8px 0}.done input{width:18px;height:18px;vertical-align:middle;margin-right:10px}.preflight label{display:block;margin:14px 0;line-height:1.5}.action-steps{padding-left:24px}.action-steps li{padding:10px 0}.action-steps p{margin:6px 0 0}.action-steps a{font-weight:600}.console-nav{display:flex;gap:12px;flex-wrap:wrap;margin-top:16px}.console-nav a{border:1px solid #444;border-radius:12px;padding:12px;text-decoration:none}.note{color:#a3a3a3;font-size:14px}.status{border-left:3px solid #e4bd68;padding:10px 16px;background:#241e13}summary{cursor:pointer;padding:12px 0}.qr-pair{display:flex;gap:32px;flex-wrap:wrap}.qr-pair img{width:180px;height:180px;background:white;border-radius:8px}.qr-pair a{display:block;max-width:480px;overflow-wrap:anywhere}button.secondary{background:transparent;border:1px solid #555}@media(max-width:650px){main{padding:18px 14px}.block{padding:18px}dl{grid-template-columns:1fr;gap:5px}dd{margin-bottom:12px}.toolbar{padding:12px}.block header a{margin-left:0}}
</style><link rel="stylesheet" href="../assets/aex-workshop.css"></head><body><div class="toolbar"><div><span class="timer" id="timer">00:00</span> <span id="pace">Ready for rehearsal</span></div><div class="controls"><button id="start">Start / resume</button><button id="pause" class="secondary">Pause</button><button id="reset" class="secondary">Reset timer</button><button id="current" class="secondary">Current block ↓</button></div></div><main>
<a class="aex-mark" href="index.html"><svg role="img" aria-label="AEX" width="76" height="36" viewBox="0 0 38 18" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M17.1268 18H13.6915L12.397 14.3751H4.58039L3.31086 18H0L6.72126 0H10.3308L17.1268 18ZM5.52636 11.7186H11.451L8.46381 3.30208L5.52636 11.7186Z" fill="currentColor"/>
<path d="M29.4616 6.18204L33.9673 0H37.6017L31.2787 8.68966L38 18H34.2411L29.3619 11.2717L24.4828 18H19.78L18.704 15.1448H22.9317L27.5696 8.78894L23.2839 2.85517H14.0723L12.9962 0H25.0056L29.4616 6.18204Z" fill="currentColor"/>
<path d="M23.4 10.0552H16.7858L15.7097 7.2H23.4V10.0552Z" fill="currentColor"/>
</svg><span>Sui Basecamp</span></a><p class="note">PRESENTER COMPANION · keep on the laptop, away from the audience display</p><h1>Trade. Guard. Hunt. Claim.</h1><p>Build Agents That Do It All. · 60 minutes · October 7, 12:30–13:30 SGT</p>
<nav class="links"><a href="index.html#s1" target="workshop-deck">Audience deck ↗</a><a href="http://127.0.0.1:8788/" target="rebalancer-runtime">Runtime console ↗</a><a href="../deploy.html" target="workshop-build">Build guide ↗</a><a href="../register.html" target="workshop-funding">Funding form ↗</a><a href="https://sui-basecamp-funding.j94fv2pvjn.chatgpt.site/operator" target="workshop-operator">Private operator controls ↗</a><a href="../" target="workshop-evidence">Live Sui lab ↗</a></nav>
<section class="preflight" id="console-controls"><h2>Open the exact console step</h2><label>Console port <select data-runtime-port aria-label="Console port"><option value="8788">8788 · existing / default</option><option value="8789">8789 · separate local rehearsal</option></select></label><p>Console: <strong data-runtime-address>http://127.0.0.1:8788</strong>. This selection updates launch commands and console links in this guide, the companion and the deck in this browser. It does not start or move a server.</p><p>These links open the separate runtime console on this laptop. Each link only opens a screen; click the named button there to perform the action. Keep the runtime terminal open. If the console cannot connect, open the <a href="../deploy.html" target="workshop-build">build guide</a> and complete the launch instructions first.</p><nav class="console-nav" aria-label="Runtime steps"><a href="http://127.0.0.1:8788/#prepare" target="rebalancer-runtime">01 Check runtime ↗</a><a href="http://127.0.0.1:8788/#configure" target="rebalancer-runtime">02 Wallet + configure ↗</a><a href="http://127.0.0.1:8788/#deploy" target="rebalancer-runtime">03 Install agent ↗</a><a href="http://127.0.0.1:8788/#run" target="rebalancer-runtime">04 Start / run ↗</a><a href="http://127.0.0.1:8788/#inspect" target="rebalancer-runtime">05 Inspect ↗</a><a href="http://127.0.0.1:8788/#modify" target="rebalancer-runtime">06 Modify ↗</a><a href="http://127.0.0.1:8788/#stop" target="rebalancer-runtime">07 Stop ↗</a></nav><p class="note">Start with 01 for a full rehearsal. “Runtime prepared” means the check passed, not that the agent is installed. Installation is 03; execution starts at 04. Existing runtime state is preserved when opening these screens.</p></section>
<div class="status"><strong>Rehearsal status</strong><p>Installation, live reads and unsigned simulation have been tested. The new workshop wallet is approved. Funding from the source account, a signed swap and the final participant allowance still need the funded rehearsal. Do not describe those as completed.</p></div>
<section class="preflight"><h2>Before the room enters</h2>
<label><input type="checkbox" data-check="runtime"> Console reachable; verify which computer runs it. Check → wallet → strategy → install → run → inspect → modify → stop.</label>
<label><input type="checkbox" data-check="wallet"> Workshop wallet funded; current balance and receipt checked. No historical example address used.</label>
<label><input type="checkbox" data-check="recipe"> One full recipe rehearsed. Save its configuration, actual output and any confirmed transaction link.</label>
<label><input type="checkbox" data-check="funding"> Allowance, total and sender reserve measured and agreed. Source account signed in privately. Operator page open; actual email-and-wallet campaign selected; registration accepts submissions independently of the reminder timer.</label>
<label><input type="checkbox" data-check="qr"> Scan both QRs from the actual projected slide. Check the full links on a laptop.</label>
<label><input type="checkbox" data-check="privacy"> Notifications hidden; credentials and participant export stay off the shared display. AEX coordinator state untouched.</label>
<details><summary>Exactly where installation happens</summary><ol><li>Install Node 24 before launching the console.</li><li>Download and unzip the kit. From its folder, launch the console:</li></ol><pre id="launch" data-port-command="shell">PORT=8788 node server.mjs --open</pre><button data-copy="launch">Copy launch command</button><p>Keep that terminal open. Choose 8789 above to launch a separate local instance; extract a fresh folder first for clean configuration. In a second terminal, from the same kit folder:</p><pre id="wallet-command">node wallet-setup.mjs</pre><button data-copy="wallet-command">Copy wallet command</button><p>Inside the console, step 01 checks the runtime. Step 02 saves the wallet and strategy. <a href="http://127.0.0.1:8788/#deploy" target="rebalancer-runtime">Step 03 Install agent</a> → click <strong>Install dependencies</strong> to run npm ci. Wait for completion. <a href="http://127.0.0.1:8788/#run" target="rebalancer-runtime">Step 04 Start / run</a> → click <strong>Run once</strong> to start the actual recipe process.</p></details>
<details id="funding-wallet-login"><summary>Connect the funding account: web wallet or CLI</summary><p>The operator key only unlocks registrations. The dashboard does not yet connect or approve transactions from a funding wallet.</p><p><strong>For one rehearsal transfer:</strong> open <a href="https://waap.xyz" target="workshop-wallet" rel="noopener">the WaaP web wallet</a>, sign in normally, choose SUI on mainnet and prepare Send to the builder’s saved address. Review the recipient, amount and gas in the wallet before approval. Record the confirmed receipt so that payment is not sent again by the payout script.</p><p><strong>For CLI funding:</strong> email-link/social web login is different from the CLI’s email/password login. Do not sign up again with an existing funded account. If it has no password, request the setup/reset email yourself:</p><pre id="funding-reset-command">WAAP_CLI_ENV=production npx --yes @human.tech/waap-cli@2.2.1 reset-password --email aex@holonym.id</pre><button data-copy="funding-reset-command">Copy password setup command</button><p>Complete the email link, then use the private funding-wallet login launcher with the new password. Completing reset signs out existing sessions. Compare the CLI’s full Sui address with the address shown in the existing web wallet before funding. This account has not yet completed that check.</p><p><a href="../funding/README.md">Full funding instructions ↗</a></p></details>
<details><summary>QR links and operator funding sequence</summary><div class="qr-pair"><div><img src="../assets/build-qr.png" alt="Build guide QR"><a href="../deploy.html">https://holonym-foundation.github.io/basecamp-builder-lab/deploy.html</a></div><div><img src="../assets/funding-qr.png" alt="Funding form QR"><a href="../register.html">https://holonym-foundation.github.io/basecamp-builder-lab/register.html</a></div></div><ol><li>Build QR first: install the kit and create the wallet.</li><li>Builders copy their Sui address into Strategy. Funding asks for email and includes that saved address. A direct Funding QR scan asks for both.</li><li>On the private operator screen, paste the private operator key and click Load private controls. Leave both checkboxes unchecked for the actual email-and-wallet workshop. For practice, select only Separate rehearsal campaign (testnet); use its separate rehearsal form. Historical code-and-wallet campaign is the old code-based flow and is not used for this workshop. Load or prepare the campaign if needed. No attendee codes. Registration does not require starting the reminder timer.</li><li>Optionally start the 15-minute reminder. It is a pacing aid: submissions remain eligible before it starts and after it ends. The server selects the first 30 unique email-and-wallet pairs; subsequent pairs join the waitlist. An explicit host stop still closes intake.</li><li>When ready, export campaign.json and responses.csv together. The payout agent creates an offline plan with approved amount, total, source address and sender reserve.</li><li>Review email/address pairs, selected recipients and total. Execute using the dedicated aex funding session and one durable ledger. Stop on unresolved results; verify each transfer receipt.</li></ol><h3>Test registration without sending funds</h3><ol><li>Select only Separate rehearsal campaign (testnet), then Load private controls.</li><li>Open the <a href="../register.html?rehearsal=1" target="workshop-funding-test">rehearsal registration form</a>. Enter a test email and a wallet address you control.</li><li>Submit once and note the registration receipt. Reload the form and repeat the same pair: it should return the same registration without taking another place.</li><li>Reload private controls and check the selected count. Export campaign.json and responses.csv and verify the email/address pair. These files are rehearsal-only; no funds are sent by this test.</li></ol><p class="note">The operator key is a host credential, never a participant requirement or a projected QR. The form does not send funds.</p></details></section>
''' + ''.join(sections)+'''
</main><script>
const timer=document.querySelector('#timer'),pace=document.querySelector('#pace');let elapsed=0,runningAt=null;
try{const saved=JSON.parse(localStorage.getItem('basecamp-presenter-clock')||'null');if(saved){elapsed=Number(saved.elapsed)||0;runningAt=saved.runningAt||null;}}catch{}
function millis(){return elapsed+(runningAt?Date.now()-runningAt:0)}function save(){localStorage.setItem('basecamp-presenter-clock',JSON.stringify({elapsed,runningAt}))}function tick(){const seconds=Math.floor(millis()/1000),minutes=seconds/60;timer.textContent=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');let active=null;document.querySelectorAll('.block').forEach(b=>{const yes=minutes>=Number(b.dataset.start)&&minutes<Number(b.dataset.end);b.classList.toggle('active',yes);if(yes)active=b;});pace.textContent=minutes>=60?'Session complete':active?active.querySelector('h2').textContent:'Ready';}
document.querySelector('#start').onclick=()=>{if(!runningAt)runningAt=Date.now();save();tick()};document.querySelector('#pause').onclick=()=>{elapsed=millis();runningAt=null;save();tick()};document.querySelector('#reset').onclick=()=>{elapsed=0;runningAt=null;save();tick()};document.querySelector('#current').onclick=()=>document.querySelector('.block.active')?.scrollIntoView({behavior:'smooth',block:'start'});
for(const c of document.querySelectorAll('[data-check]')){c.checked=localStorage.getItem('basecamp-presenter-'+c.dataset.check)==='true';c.onchange=()=>localStorage.setItem('basecamp-presenter-'+c.dataset.check,String(c.checked));}
for(const b of document.querySelectorAll('[data-copy]'))b.onclick=async()=>{try{await navigator.clipboard.writeText(document.getElementById(b.dataset.copy).textContent);b.textContent='Copied'}catch{b.textContent='Select and copy the command above'}};
tick();setInterval(tick,1000);
</script><script src="../assets/runtime-port.js"></script></body></html>'''
(root/'deck/presenter.html').write_text(page)
(root/'deck/presenter.txt').write_text('CONSOLE STEPS (open screen, then click its button)\n\n'+'\n\n'.join(f'{label} | {runtime}#{key}\n{instruction}' for key,(label,instruction) in steps.items())+'\n\n'+'BASECAMP PRESENTER COMPANION\n\n'+'\n\n'.join(f'{a:02}–{b:02} MIN | {title}\nSCREEN: {screen}\nDO: {action}\nSAY: {say}\nLOOK FOR: {expected}\nIF STUCK: {fallback}' for a,b,title,sid,screen,action,say,expected,fallback in blocks))
