"""Refresh the existing v4 deck and presenter cues for the local builder route."""
import base64,html,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def cue(show,do,say,look,fallback):
    return f'SHOW: {show}\nDO: {do}\nSAY: {say}\nLOOK FOR: {look}\nFALLBACK: {fallback}\nPresenter notes stay on a private display. AEX rehearsal state belongs to Studio.'
updates={
's1':dict(title='Rebalance.\nProtect.',content='Build a Sui decision loop. Change it. Check the evidence.'),
's10':dict(title='Separate the four budgets.',content=[['AEX + WaaP','Runtime and signing costs.\nSeparate from token capital.'],['Agent capital','Funds for a measured live recipe.\nLocal lessons use sample positions.'],['Gas','Native SUI for transactions.\nNo gas for the read-only lesson.']],notes=cue('Slides','Explain AEX fees, WaaP fees, gas and position capital as separate allocations. No amount is approved yet. Local workshop loops incur none of the hosted/signing fees.','Fund the job we actually run.','No suggestion that a lesson or a code is a funded position.','If the funded recipe is not rehearsed, keep the room on the decision loops.')),
's12':dict(title='Two Sui jobs to build.',kind='two',content=[['Sui Rebalancer','Read a price. Compare an allocation.\nPropose the next move.'],['Liquidation Guardian','Watch lending risk. Cap the response.\nStop when data is unknown.']],label='SUI BUILD CHOICES',drills=[],icons=[],arrows=False,notes=cue('Slide → builder guide','Introduce the two choices. Rebalancer uses live Sui price + sample holdings. Guardian lesson uses labelled scenarios. Open All starter sources to show seven public skills, one public scaffolded activity, hosted starters and the wider docs library.','Choose the problem you want your agent to solve.','The full Guardian is not in the checked public repo. These are workshop loops, not the full AEX deployments.','Browser lessons need no wallet.')),
's13':dict(layout=None,title='Tour the agent, then its decision.',content=[['Inputs → decision','Choose a recipe. Inspect its inputs.\nFind the run output and controls.'],['Authority → evidence','Separate a proposal from execution.\nCheck the chain after an action.']],label='SWITCH TO BUILDER GUIDE · 18–20 MIN',notes=cue('build.html → chosen card → source file','Open build.html. Click Rebalancer, then Guardian. Show download, command, change, output and source links. If the complete AEX flow passed coordinator rehearsal, optionally show its catalogue → starter detail → configure → launch → output → cost → stop; otherwise stay on this local tour.','The same job can be packaged in a runtime later. Today we can inspect the decision directly.','Participants know where to run and where to read output.','Do not spend this block repairing AEX.')),
's14':dict(title='Choose your build.',content=[['Rebalancer','Live price + sample allocation.\nRun locally or in your browser.'],['Guardian','Risk scenario + capped proposal.\nRun locally or in your browser.']],label='OPEN THE BUILDER GUIDE · 20–23 MIN',notes=cue('QR → build.html → terminal','Scan the guide QR. Download workshop-agent.mjs. Open a terminal in its folder. Run node --version (Node 24), then node workshop-agent.mjs rebalancer OR node workshop-agent.mjs guardian --scenario at-risk. No npm install. Open funding registration now only when a real form and approved amount/network are ready; it closes 15 minutes later. Click Funding QR below the builder QR to show the registration link, then Build QR to return.','Each person chooses one build. You can finish it without AEX or a funded wallet.','JSON output or the browser Run once alternative.','After 45 seconds of setup trouble, use the identical browser lesson.')),
's15':dict(title='Vote for the walkthrough.',kind='two',content=[['Rebalancer','How should a portfolio react?\nLive Sui price, sample holdings.'],['Guardian','When should protection act?\nRisk scenarios, capped response.']],label='SHOW OF HANDS · BOTH PATHS STAY AVAILABLE',notes=cue('Slide → show of hands','Take a 30-second vote between the two lessons. Lead with the winner; each builder can still follow the other card.','Both paths end with an explainable decision and real Sui evidence.','One choice, no external poll signup.','Default to Rebalancer if unclear.')),
's16':dict(title='Run one decision loop.',kind='prompt',content='node workshop-agent.mjs rebalancer\n\nnode workshop-agent.mjs guardian --scenario at-risk',label='TERMINAL OR BROWSER · 24–27 MIN',notes=cue('Terminal → downloaded source → JSON output','Run only the chosen command. Rebalancer: identify price, checkpoint, simulated holdings, decision, proposed value. Guardian: identify healthFactor 1.1, target 1.3, proposedRepayUsd 10, targetRestoredWithinCap false. Show the few lines of rebalance() or guardian() in an editor.','A proposal is a result we can inspect before granting action authority.','Rebalancer reads mainnet. Guardian explicitly says SIMULATED. Neither signs.','Network failure: run Guardian locally; never label its scenario a live lending position.')),
's17':dict(title='Change the decision. Check why.',kind='two',content=[['Rebalancer','Target: 50% → 70%.\nCompare HOLD, BUY or SELL.'],['Guardian','At risk → healthy → unknown.\nExplain when the loop must stop.']],label='EDITOR → TERMINAL → EVIDENCE · 27–31 MIN',drills=[],icons=[],arrows=False,notes=cue('Terminal / browser → live Sui lab → explorer','Rebalancer: node workshop-agent.mjs rebalancer --target 0.7. Guardian: node workshop-agent.mjs guardian --scenario healthy then --scenario unknown. Open a real pool transaction in the lab; match status, balances and gas in Suiscan. The linked Guardian transaction is a prior demo, not today’s execution. A current swap/repay only substitutes after its own funded rehearsal.','Changing the rule changes a proposal. The chain receipt separately proves what actually executed.','Guardian unknown branch STOP_UNKNOWN_DATA; a cap can be insufficient. Match actual transaction type and digest.','If live data fails show an explicitly dated receipt or use the scenario; do not send a neighbour transfer as a substitute for a rebalance.')),
's18':dict(title='Save the result. Know the cost.',content=[['Keep the evidence','Input + changed setting + output.\nA real receipt only if one exists.'],['End the run','One-shot scripts exit on completion.\nCtrl+C stops a pending read.']],label='OUTPUT → COST → STOP · 31–34 MIN',drills=[],icons=[],notes=cue('Terminal → guide Save browser output','Save output to a local file or use Save browser output. Explain the local loop has no paid inference, WaaP signing, AEX fee or gas. Full agents have separate runtime, fees and capital. Confirm the process has exited.','A stopping point is part of the recipe.','No running process and no claimed swap or repay from the lesson.','Do not log out or modify shared AEX sessions.')),
's19':dict(title='Your turn.',content='Choose one build. Change one rule.\nShow the decision and its evidence.',notes=cue('Builder QR → laptops / phones','Open build.html. Builders choose either card. Funding registration closes 15 minutes after its operator-controlled opening, not on page load. If opened at minute 20, close at 35; validate export separately before any payout.','Everyone can build; up to 30 valid registrations receive the measured funding allowance.','Working lesson for each participant or pair.','Use Guardian scenarios offline or Hunt for a non-chain research exercise.')),
's20':dict(title='Build. Compare. Explain.',kind='two',content=[['Sui Rebalancer','Change target or rebalance band.\nExplain the proposed allocation.'],['Liquidation Guardian','Try healthy, at-risk and unknown.\nExplain the cap and stop condition.']],label='LOCAL BUILD / BROWSER · 35–46 MIN',notes=cue('Selected lesson → source → output','Let the room work. Rebalancer edit target or band; Guardian edit target health factor or scenario. Keep all lessons in decision-only mode. Advanced builders follow the public Rebalancer guide in DRY_RUN=1 only after wallet/coin setup; the docs scaffold shortcut is not in the checked public registry. No Guardian full public download exists yet.','Make one change you can explain.','Output labels show live input versus simulated position.','Use browser lessons if Node is unavailable; do not open loans to create a demo position.')),
's23':dict(content=[['Continue your build','Public Rebalancer guide.\nSuilend reference + workshop source.'],['Explore the catalogue','Seven public skills + Cetus scaffold.\nMore recipes in the docs.']],qr=False,notes=cue('build.html#library','Link the actual sources. Full Guardian publication is a remaining gap, not a shipped starter. Hosted AEX has six starter names; public skills and docs cover a different set.','Keep your code, output and next experiment.','No blanket claim that every hosted agent is a public standalone download.','Local lesson remains usable independently.')),
's26':dict(content=[['Setup is stuck','Open the same lesson in a browser.\nGuardian scenarios work without RPC.'],['Funding is full','30 funded places; then waitlist.\nKeep building without a grant.']],notes=cue('Builder guide → chosen lesson','Use the browser route or pair up. Funding and AEX admission are separate from access to the public exercises. Only share the actual live registration/waitlist form.','You can complete the lesson while funding is processed.','No credentials or private codes projected.','Hunt is the non-chain fallback.')),
's29':dict(title='The command card.',content='node workshop-agent.mjs rebalancer --target 0.7\n\nnode workshop-agent.mjs guardian --scenario healthy\nnode workshop-agent.mjs guardian --scenario unknown',label='NODE 24 · NO INSTALL · ONE RUN THEN EXIT',notes='Download workshop-agent.mjs from build.html. Open terminal in the download folder. Commands are decision-only. No wallet sessions, keys or AEX deployment. For the full recipe use the public guide and its own prerequisites.'),
's30':dict(content=[['Presentation','Audience deck + private presenter guide.\nTwo lead recipes.'],['Build','build.html + source + clean terminal.\nLocal lesson or browser alternative.'],['Evidence','Live Sui lab + matching explorer.\nFunding form on operator screen.']],notes='Keep presenter notes private: N opens notes in the audience deck itself. Download workshop-agent.mjs ahead of time. Pre-open build.html, live pool lab and explorer. AEX remains optional after coordinator acceptance. Keep signup/email/private codes/session files off screen.')
}

# Keep the fixed programme title and make the live choreography explicit.
updates.update({
's1':dict(title='Trade. Guard.\nHunt. Claim.',content='Build Agents That Do It All.'),
's13':dict(layout=None,title='Watch the flow first.',content=[['One recipe','Choose Rebalancer or Guardian.\nInputs → decision → evidence.'],['One walkthrough','I show the controls first.\nWe run it together after the QR.']],label='WATCH FIRST · 18–20 MIN',notes=cue('Deck → embedded walkthrough → back to slides','Click Run Rebalancer or Run Guardian. Point to the numbered steps without running ahead. Return to slide 15 for the builder QR. An AEX app tour is optional only if the coordinator has accepted the full launch/output/cost/stop path.','First I will show you the route. Then we will run it together.','Everyone sees where the run, change, evidence and save controls are.','Use the browser lesson; no terminal setup is required.')),
's14':dict(title='Scan. Open. Follow along.',content=[['1 · Open the guide','Scan Build QR. Choose a recipe.\nKeep the page open.'],['2 · Follow with me','We run the first example together.\nYour own experiment comes next.']],label='JOIN THE GUIDED BUILD · 20–23 MIN',notes=cue('Builder QR → optional funding QR → back to Build QR','At 20:00 show Build QR. Everyone opens build.html. At about 21:00, if funding is configured, open the 15-minute operator window and show Funding QR briefly. Return to Build QR. A window opened at 21:00 closes at 36:00. People can register in parallel; it does not block the lesson.','Open this guide now and follow my first run. After minute 34 you will make your own change.','Builder QR and funding QR have distinct labels. Neither scanning nor showing a QR opens intake.','Skip the funding detour if the allowance is not ready; everyone can do the read-only build.')),
's15':dict(title='We build this one together.',kind='two',content=[['Rebalancer','Live Sui price + sample allocation.\nClick through with the presenter.'],['Guardian','Lending scenarios + capped response.\nSame follow-along structure.']],label='FOLLOW WITH ME · 23–24 MIN',notes=cue('Deck → Run Rebalancer (default) or Run Guardian','Take a quick show of hands if needed. Click the chosen Run button to open the embedded walkthrough. Lead ONE recipe, not both. Participants can follow it or choose the other card. Leave the walkthrough open for the next ten minutes.','Keep your guide open and click each step with me.','The presenter is in the embedded demo; the room is on the same builder page.','Default to Rebalancer; use Guardian scenarios if live reads fail.')),
's16':dict(title='Click Run. Inspect the result.',kind='two',content=[['Read → decide','Run the baseline in the walkthrough.\nIdentify the inputs and proposal.'],['Explain the boundary','Rebalancer: live price, sample holdings.\nGuardian: labelled risk scenarios.']],label='EMBEDDED WALKTHROUGH · 24–27 MIN',notes=cue('Embedded walkthrough step 1 → result','Click the baseline Run control. Read the summary, then expand the raw output if useful. Rebalancer: price, checkpoint, target and proposed change. Guardian: health factor, cap and whether it restores the target. No terminal typing.','A proposal is something we can inspect before granting action authority.','An actual browser execution result. No swap or repayment is claimed.','If the read fails, show the error and retry once or use Guardian.')),
's17':dict(title='Change one rule. Compare.',kind='two',content=[['Rebalancer','Click the 70% target step.\nCompare it with the first run.'],['Guardian','Click healthy, then unknown data.\nCompare the response and stop.']],label='EMBEDDED WALKTHROUGH · 27–31 MIN',drills=[],icons=[],arrows=False,notes=cue('Walkthrough change/compare → evidence','Use the next-step buttons to run the changed setting. Compare the saved baseline and new result. For Guardian, run the unknown-data case too. Then open the real Sui evidence link. Match the digest/status/balances/gas to the explorer; the historical Guardian receipt is a previous demo.','The rule changes a proposal. A chain receipt proves a separate executed action.','Both outputs remain visible for comparison. Unknown data stops Guardian.','Stay on the labelled scenario or previous receipt if the network fails; never fabricate a new transaction.')),
's18':dict(title='Save our example. End the run.',content=[['Keep the comparison','Save the inputs, change and outputs.\nKeep the evidence link.'],['Know the cost','Read-only lesson: no transaction fee.\nEach run finishes on its own.']],label='SAVE → DONE · 31–34 MIN',notes=cue('Walkthrough save step → back to slide 20','Click Save to download the comparison. Each run is one-shot. Explain that the optional coding-agent wrapper can have its normal model cost; this browser helper makes no model or signing call. Close the walkthrough and show Your turn.','That was our shared example. Now you will make your own change.','Saved evidence and a clear handoff to independent work.','If no successful result exists, save the error and next diagnostic step without calling it a success.')),
's19':dict(title='Now make it yours.',content='Your own recipe. Your own change.\nRun it, compare it, explain it.',notes=cue('Independent-build QR → participant screens','At 34:00 clearly say the guided demonstration is over. Show Build QR again for anyone who missed it. People may restart the walkthrough, switch recipe, or use advanced controls to make their own change. If funding opened at 21:00 it closes at 36:00; the operator handles export separately.','You now have 17 minutes for your own experiment. Pick one change you can explain.','Everyone knows this is independent work, not another presenter demo.','Pair up or use Guardian scenarios if connectivity is poor.')),
's20':dict(title='Your experiment. Your evidence.',kind='two',content=[['Sui Rebalancer','Pick your own target or band.\nSave what changed in the decision.'],['Liquidation Guardian','Pick a scenario or risk target.\nExplain the cap and unknown-data stop.']],label='BUILD ON YOUR OWN · 35–46 MIN',notes=cue('Participant builder pages','Circulate rather than continue a second presentation. Builders can repeat the click-through or expand advanced controls. Optional local code/download is for people who want it; it is not required.','Try one small change, compare the output, and prepare a short explanation.','A chosen setting and an output the participant can explain.','Use the browser route or work in pairs. Full funded swaps/repayments are outside this lesson unless separately rehearsed.')),
})

base='https://holonym-foundation.github.io/basecamp-builder-lab/'
qr=base64.b64encode((ROOT/'assets/build-qr.png').read_bytes()).decode()
js='''<script>(()=>{
const base=BASE,defs={build:['Choose your build ↗',base+'build.html'],library:['Starter sources ↗',base+'build.html#library'],guard:['Live Sui evidence ↗',base],hunt:['Non-chain Hunt ↗',base+'hunt.html'],receipt:['Previous pool receipt ↗',base+'?tx=Fvdxzog5tBYp3D4gg85PJxd6j4embkbcKyMKowhYnFV8'],guardian:['Previous Guardian demo ↗','https://suivision.xyz/txblock/4Fpevq1op4CiaQT79ZSvrQE8Jcc8reh8zvp5kjCPgiMG']};
const links={s12:['library'],s13:['build'],s14:['build'],s15:['build'],s16:['build'],s17:['receipt','guardian'],s18:['build'],s19:['build'],s20:['build'],s23:['library'],s25:['hunt'],s26:['build','hunt'],s29:['build'],s30:['build','guard']};
function protect(a){a.target='_blank';a.rel='noopener noreferrer';for(const type of ['click','keydown'])a.addEventListener(type,e=>e.stopPropagation());}
for(const [id,keys]of Object.entries(links)){const nav=document.createElement('nav');nav.className='workshop-actions';nav.setAttribute('aria-label','Workshop links');for(const key of keys){const a=document.createElement('a');a.className='workshop-link';a.textContent=defs[key][0];a.href=defs[key][1];protect(a);nav.append(a);}document.querySelector('#slide-'+id).append(nav);}
for(const id of ['s14','s19']){const box=document.createElement('div');box.className='workshop-qr';const a=document.createElement('a');a.href=base+'build.html';protect(a);const img=document.createElement('img');img.src='data:image/png;base64,QR';img.alt='Scan to choose Rebalancer or Guardian';a.append(img,document.createTextNode('Choose your build'));const p=document.createElement('p');p.textContent='Local code + browser lesson';box.append(a,p);document.querySelector('#slide-'+id).append(box);}
})();</script>'''.replace('BASE',json.dumps(base)).replace('QR',qr)
funding_config = ROOT/'funding-registration.json'
if funding_config.exists():
    registration = json.loads(funding_config.read_text())
    funding_qr = base64.b64encode((ROOT/'assets/funding-qr.png').read_bytes()).decode()
    js += '''<script>(()=>{
const form=FORM, fundingQR='data:image/png;base64,FUNDING_IMAGE';
for(const id of ['s14','s19']){
 const slide=document.querySelector('#slide-'+id),box=slide.querySelector('.workshop-qr'),a=box.querySelector('a'),img=box.querySelector('img'),p=box.querySelector('p');
 const buildURL=a.href,buildQR=img.src;
 const controls=document.createElement('div');controls.style.cssText='display:flex;gap:12px;justify-content:center;margin-top:18px';
 for(const mode of ['Build QR','Funding QR']){
  const b=document.createElement('button');b.type='button';b.className='workshop-link secondary';b.style.cssText='font-size:21px;padding:10px 16px;cursor:pointer';b.textContent=mode;b.setAttribute('aria-pressed',String(mode==='Build QR'));
  for(const type of ['click','keydown'])b.addEventListener(type,e=>e.stopPropagation());
  b.addEventListener('click',()=>{const funding=mode==='Funding QR';a.href=funding?form:buildURL;img.src=funding?fundingQR:buildQR;img.alt=funding?'Scan to request workshop funding':'Scan to choose Rebalancer or Guardian';a.lastChild.textContent=funding?'Workshop funding':'Choose your build';p.textContent=funding?'15-minute window · 30 funded places':'Local code + browser lesson';controls.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));});controls.append(b);
 }
 box.append(controls);
}
})();</script>'''.replace('FORM',json.dumps(registration['url'])).replace('FUNDING_IMAGE',funding_qr)
js += '<script>' + (ROOT/'deck/demo-overlay.js').read_text() + '</script>'
for name in ['index.html','aex-v4.html']:
    path=ROOT/'deck'/name;p=path.read_text()
    match=re.search(r'window.SLIDES\s*=\s*(\[.*?\]);',p,re.S);slides=json.loads(match[1])
    for s in slides:
        if s['id'] in updates:s.update(updates[s['id']])
    # Same participant route in both variants; AEX tour remains an optional presenter cue.
    p=p[:match.start(1)]+json.dumps(slides,ensure_ascii=False)+p[match.end(1):]
    start=p.find('<script>(()=>{\nconst base=')
    if start!=-1:p=p[:start]+js+'</body></html>\n'
    p=p.replace('grid-template-columns:1fr;gap:42px','grid-template-columns:1fr!important;gap:42px')
    if 'hashchange' not in p:
        p=p.replace('fit(); go(start, false);', "fit(); go(start, false);\naddEventListener('hashchange', () => { const i = fromHash(); if (i >= 0) { if (drill.open) closeDrill(); go(i, false); } });")
    p=re.sub(r'<title>.*?</title>','<title>Trade. Guard. Hunt. Claim. Build Agents That Do It All.</title>',p,flags=re.S)
    if '#slide-s19 .h{bottom:430px}' not in p:
        p=p.replace('#slide-s14 .card h3{font-size:46px}', '#slide-s19 .h{bottom:430px}#slide-s14 .card h3{font-size:46px}')
    p=p.replace('</head>','<style>#slide-s19 .h{bottom:430px}#slide-s14 .card h3{font-size:46px}#slide-s14 .card p{font-size:30px}#slide-s16 pre,#slide-s29 pre{font-size:34px}#slide-s12 .cols,#slide-s17 .cols,#slide-s20 .cols{bottom:265px}</style></head>') if '#slide-s14 .card h3' not in p else p
    path.write_text(p)
# Presenter guide is generated from the same slide cues; it cannot silently drift.
intro='''<h1>Trade. Guard. Hunt. Claim.</h1><p>Build Agents That Do It All.</p><p>Private presenter guide · October 7, 12:30–13:30 SGT · 60 attendees · laptop-first</p><nav><a href="index.html" target="deck">Audience deck</a> · <a href="../build.html" target="build">Builder guide</a> · <a href="../index.html" target="evidence">Live Sui lab</a> · <a href="../register.html" target="registration">Funding form</a> · <a href="https://sui-basecamp-funding.j94fv2pvjn.chatgpt.site/operator" target="operator">Operator controls</a></nav><section><h2>Before the room enters</h2><ol><li>Click through both embedded lessons once. No terminal is needed for the presentation. Keep the downloadable Node source as an optional backup. Test both QR links on a phone and venue Wi-Fi.</li><li>Keep this page on your private screen. The deck’s N key exposes notes in the audience window.</li><li>Rebalancer = live price + sample holdings. Guardian = labelled risk scenarios. Neither is a deployed AEX agent or a live trade.</li><li>Pre-open a real Sui transaction and matching explorer. A prior Guardian receipt is historical evidence. Only add a live swap/repay if that exact funded route passes rehearsal.</li><li>Funding: operator opens a real form for 15 minutes, up to 30 validated recipients then waitlist. Amount remains unset until measured. Check the real registration link before projecting its separate QR.</li><li>AEX runtime/session state stays with Studio. No venue resubmission from this update.</li></ol></section><section><h2>Keep the original 60-minute shape</h2><p>0–6 why agents · 6–11 deployment · 11–16 authority + budget · 16–20 agent tour · 20–34 guided build · 34–51 open build · 51–57 share · 57–60 close.</p><p>At 18: show the walkthrough controls without running ahead. At 20: show Build QR; everyone opens the guide. Around 21: optionally open funding intake and briefly show Funding QR, then return to Build QR. At 23: choose one recipe and open its embedded walkthrough. At 24: click the baseline Run together. At 27: click the change step and compare. At 30: inspect real Sui evidence. At 32: save. At 34: explicitly hand over to independent building. Funding opened at 21 closes at 36; the operator exports separately. At 51: invite two short shares.</p></section>'''
sections=[]
for s in slides:
    sections.append(f'<section id="{s["id"]}"><div class="time">{html.escape(s["time"])}</div><h2>{html.escape(s["title"])}</h2><a href="index.html#{s["id"]}" target="deck">Open slide {s["num"]} ↗</a><pre>{html.escape(s["notes"])}</pre></section>')
page='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Basecamp · presenter guide</title><style>body{background:#0b0b0d;color:#eee;font:18px/1.55 system-ui;margin:0}main{max-width:1060px;margin:auto;padding:36px 24px}section{padding:24px;border:1px solid #38383c;border-radius:16px;margin:24px 0}h1{font-size:48px}h2{font-size:28px}a,.time{color:#2ed0bd}pre{white-space:pre-wrap;font:inherit;color:#bdbbb8}li{margin:14px 0}</style></head><body><main>'+intro+''.join(sections)+'</main></body></html>'
(ROOT/'deck/presenter.html').write_text(page)
(ROOT/'deck/presenter.txt').write_text('TRADE. GUARD. HUNT. CLAIM. BUILD AGENTS THAT DO IT ALL.\n\n'+ '\n\n'.join(f'{s["time"]} | {s["title"]}\n{s["notes"]}' for s in slides))
