"""Refresh the existing v4 deck and presenter cues for the local builder route."""
import base64,html,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def cue(show,do,say,look,fallback):
    return f'SHOW: {show}\nDO: {do}\nSAY: {say}\nLOOK FOR: {look}\nFALLBACK: {fallback}\nPresenter notes stay on a private display. AEX rehearsal state belongs to Studio.'
updates={
's1':dict(title='Rebalance.\nProtect.',content='Build a Sui decision loop. Change it. Check the evidence.'),
's10':dict(title='Separate the four budgets.',content=[['AEX + WaaP','Runtime and signing costs.\nSeparate from token capital.'],['Agent capital','Funds for a measured live recipe.\nLocal lessons use sample positions.'],['Gas','Native SUI for transactions.\nNo gas for the read-only lesson.']],notes=cue('Slides','Explain AEX fees, WaaP fees, gas and position capital as separate allocations. No amount is approved yet. Local workshop loops incur none of the hosted/signing fees.','Fund the job we actually run.','No suggestion that a lesson or a code is a funded position.','If the funded recipe is not rehearsed, keep the room on the decision loops.')),
's12':dict(title='Two Sui jobs to build.',kind='two',content=[['Sui Rebalancer','Read a price. Compare an allocation.\nPropose the next move.'],['Liquidation Guardian','Watch lending risk. Cap the response.\nStop when data is unknown.']],label='SUI BUILD CHOICES',drills=[],icons=[],arrows=False,notes=cue('Slide → builder guide','Introduce the two choices. Rebalancer uses live Sui price + sample holdings. Guardian lesson uses labelled scenarios. Open All starter sources to show seven public skills, one public scaffolded activity, hosted starters and the wider docs library.','Choose the problem you want your agent to solve.','The full Guardian is not in the checked public repo. These are workshop loops, not the full AEX deployments.','Browser lessons need no wallet.')),
's13':dict(layout=None,title='Tour the agent, then its decision.',content=[['Inputs → decision','Choose a recipe. Inspect its inputs.\nFind the run output and controls.'],['Authority → evidence','Separate a proposal from execution.\nCheck the chain after an action.']],label='SWITCH TO BUILDER GUIDE · 18–20 MIN',notes=cue('build.html → chosen card → source file','Open build.html. Click Rebalancer, then Guardian. Show download, command, change, output and source links. If the complete AEX flow passed coordinator rehearsal, optionally show its catalogue → starter detail → configure → launch → output → cost → stop; otherwise stay on this local tour.','The same job can be packaged in a runtime later. Today we can inspect the decision directly.','Participants know where to run and where to read output.','Do not spend this block repairing AEX.')),
's14':dict(title='Rebalancer deployment kit.',content=[['Rebalancer','Live price + sample allocation.\nRun locally or in your browser.'],['Guardian','Risk scenario + capped proposal.\nRun locally or in your browser.']],label='OPEN THE BUILDER GUIDE · 20–23 MIN',notes=cue('QR → build.html → terminal','Scan the guide QR. Download workshop-agent.mjs. Open a terminal in its folder. Run node --version (Node 24), then node workshop-agent.mjs rebalancer OR node workshop-agent.mjs guardian --scenario at-risk. No npm install. Open funding registration now only when a real form and approved amount/network are ready; it closes 15 minutes later. Click Funding QR below the builder QR to show the registration link, then Build QR to return.','Each person chooses one build. You can finish it without AEX or a funded wallet.','JSON output or the browser Run once alternative.','After 45 seconds of setup trouble, use the identical browser lesson.')),
's15':dict(title='Vote for the walkthrough.',kind='two',content=[['Rebalancer','How should a portfolio react?\nLive Sui price, sample holdings.'],['Guardian','When should protection act?\nRisk scenarios, capped response.']],label='SHOW OF HANDS · BOTH PATHS STAY AVAILABLE',notes=cue('Slide → show of hands','Take a 30-second vote between the two lessons. Lead with the winner; each builder can still follow the other card.','Both paths end with an explainable decision and real Sui evidence.','One choice, no external poll signup.','Default to Rebalancer if unclear.')),
's16':dict(title='Run one decision loop.',kind='prompt',content='node workshop-agent.mjs rebalancer\n\nnode workshop-agent.mjs guardian --scenario at-risk',label='TERMINAL OR BROWSER · 24–27 MIN',notes=cue('Terminal → downloaded source → JSON output','Run only the chosen command. Rebalancer: identify price, checkpoint, simulated holdings, decision, proposed value. Guardian: identify healthFactor 1.1, target 1.3, proposedRepayUsd 10, targetRestoredWithinCap false. Show the few lines of rebalance() or guardian() in an editor.','A proposal is a result we can inspect before granting action authority.','Rebalancer reads mainnet. Guardian explicitly says SIMULATED. Neither signs.','Network failure: run Guardian locally; never label its scenario a live lending position.')),
's17':dict(title='Change the decision. Check why.',kind='two',content=[['Rebalancer','Target: 50% → 70%.\nCompare HOLD, BUY or SELL.'],['Guardian','At risk → healthy → unknown.\nExplain when the loop must stop.']],label='EDITOR → TERMINAL → EVIDENCE · 27–31 MIN',drills=[],icons=[],arrows=False,notes=cue('Terminal / browser → live Sui lab → explorer','Rebalancer: node workshop-agent.mjs rebalancer --target 0.7. Guardian: node workshop-agent.mjs guardian --scenario healthy then --scenario unknown. Open a real pool transaction in the lab; match status, balances and gas in Suiscan. The linked Guardian transaction is a prior demo, not today’s execution. A current swap/repay only substitutes after its own funded rehearsal.','Changing the rule changes a proposal. The chain receipt separately proves what actually executed.','Guardian unknown branch STOP_UNKNOWN_DATA; a cap can be insufficient. Match actual transaction type and digest.','If live data fails show an explicitly dated receipt or use the scenario; do not send a neighbour transfer as a substitute for a rebalance.')),
's18':dict(title='Save the result. Know the cost.',content=[['Keep the evidence','Input + changed setting + output.\nA real receipt only if one exists.'],['End the run','One-shot scripts exit on completion.\nCtrl+C stops a pending read.']],label='OUTPUT → COST → STOP · 31–34 MIN',drills=[],icons=[],notes=cue('Terminal → guide Save browser output','Save output to a local file or use Save browser output. Explain the local loop has no paid inference, WaaP signing, AEX fee or gas. Full agents have separate runtime, fees and capital. Confirm the process has exited.','A stopping point is part of the recipe.','No running process and no claimed swap or repay from the lesson.','Do not log out or modify shared AEX sessions.')),
's19':dict(title='Your turn.',content='Choose one build. Change one rule.\nShow the decision and its evidence.',notes=cue('Builder QR → laptops / phones','Open build.html. Builders choose either card. Funding registration closes 15 minutes after its operator-controlled opening, not on page load. If opened at minute 20, close at 35; validate export separately before any payout.','Everyone can build; up to 30 valid registrations receive the measured funding allowance.','Working lesson for each participant or pair.','Use Guardian scenarios offline or Hunt for a non-chain research exercise.')),
's20':dict(title='Build. Compare. Explain.',kind='two',content=[['Sui Rebalancer','Change target or rebalance band.\nExplain the proposed allocation.'],['Liquidation Guardian','Try healthy, at-risk and unknown.\nExplain the cap and stop condition.']],label='LOCAL BUILD / BROWSER · 35–46 MIN',notes=cue('Selected lesson → source → output','Let the room work. Rebalancer edit target or band; Guardian edit target health factor or scenario. Keep all lessons in decision-only mode. Advanced builders follow the public Rebalancer guide in DRY_RUN=1 only after wallet/coin setup; the docs scaffold shortcut is not in the checked public registry. No Guardian full public download exists yet.','Make one change you can explain.','Output labels show live input versus simulated position.','Use browser lessons if Node is unavailable; do not open loans to create a demo position.')),
's23':dict(content=[['Continue your build','Public Rebalancer guide.\nSuilend reference + workshop source.'],['Explore the catalogue','Seven public skills + Cetus scaffold.\nMore recipes in the docs.']],qr=False,notes=cue('build.html#library','Link the actual sources. Full Guardian publication is a remaining gap, not a shipped starter. Hosted AEX has six starter names; public skills and docs cover a different set.','Keep your code, output and next experiment.','No blanket claim that every hosted agent is a public standalone download.','Local lesson remains usable independently.')),
's26':dict(content=[['Setup is stuck','Open the same lesson in a browser.\nGuardian scenarios work without RPC.'],['Funding is full','30 funded places; then waitlist.\nKeep building without a grant.']],notes=cue('Builder guide → chosen lesson','Use the browser route or pair up. Funding and AEX admission are separate from access to the public exercises. Only share the actual live registration/waitlist form.','You can complete the lesson while funding is processed.','No credentials or private codes projected.','Hunt is the non-chain fallback.')),
's29':dict(title='The command card.',content='node workshop-agent.mjs rebalancer --target 0.7\n\nnode workshop-agent.mjs guardian --scenario healthy\nnode workshop-agent.mjs guardian --scenario unknown',label='NODE 24 · NO INSTALL · ONE RUN THEN EXIT',notes='Download workshop-agent.mjs from build.html. Open terminal in the download folder. Commands are decision-only. No wallet sessions, keys or AEX deployment. For the full recipe use the public guide and its own prerequisites.'),
's30':dict(content=[['Presentation','Audience deck + private presenter guide.\nTwo lead recipes.'],['Build','build.html + source + clean terminal.\nLocal lesson or browser alternative.'],['Evidence','Live Sui lab + matching explorer.\nFunding form on operator screen.']],notes='Keep presenter notes private: N opens notes in the audience deck itself. Download workshop-agent.mjs ahead of time. Pre-open build.html, live pool lab and explorer. AEX remains optional after coordinator acceptance. Keep signup/email/private codes/session files off screen.')
}

# Keep the fixed programme title and make the live choreography explicit.
updates.update({
's1':dict(title='Trade. Guard.\nHunt. Claim.',content='Build Agents That Do It All.'),
's13':dict(layout=None,title='Inputs. Rules. Authority.',content=[['Sui Rebalancer', 'Price + holdings + target.\nA proposed allocation change.'], ['Liquidation Guardian', 'Debt + collateral + risk limit.\nA capped protective response.']],label='AGENT DECISION FLOW · 18–20 MIN',notes=cue('Deck → embedded walkthrough → back to slides','Click Open Sui Rebalancer or Open Liquidation Guardian. Point to the numbered steps without running ahead. Return to slide 15 for the builder QR. An AEX app tour is optional only if the coordinator has accepted the full launch/output/cost/stop path.','First I will show you the route. Then we will run it together.','Everyone sees where the run, change, evidence and save controls are.','Use the browser lesson; no terminal setup is required.')),
's14':dict(title='Choose a Sui recipe.',content=[['Sui Rebalancer', 'Live Sui price + sample allocation.\nInspect a proposed portfolio change.'], ['Liquidation Guardian', 'Labelled lending scenarios.\nInspect a capped protective response.']],label='RECIPES + SOURCE · 20–23 MIN',notes=cue('Builder QR → optional funding QR → back to Build QR','At 20:00 show Build QR. Everyone opens build.html. At about 21:00, if funding is configured, open the 15-minute operator window and show Funding QR briefly. Return to Build QR. A window opened at 21:00 closes at 36:00. People can register in parallel; it does not block the lesson.','Open this guide now and follow my first run. After minute 34 you will make your own change.','Builder QR and funding QR have distinct labels. Neither scanning nor showing a QR opens intake.','Skip the funding detour if the allowance is not ready; everyone can do the read-only build.')),
's15':dict(title='From input to decision.',kind='two',content=[['Sui Rebalancer', 'Price + sample holdings → allocation.\nA proposed buy, sell or hold.'], ['Liquidation Guardian', 'Collateral + debt → health factor.\nA capped repayment proposal.']],label='RECIPE LOGIC · 23–24 MIN',notes=cue('Deck → Run Rebalancer (default) or Run Guardian','Take a quick show of hands if needed. Click the chosen recipe button to open the embedded walkthrough. Lead ONE recipe, not both. Participants can follow it or choose the other card. Leave the walkthrough open for the next ten minutes.','Keep your guide open and click each step with me.','The presenter is in the embedded demo; the room is on the same builder page.','Default to Rebalancer; use Guardian scenarios if live reads fail.')),
's16':dict(title='Inspect the first decision.',kind='two',content=[['Inputs → proposal', 'Run the baseline recipe.\nInspect the rule and its result.'], ['Execution boundary', 'Rebalancer: live price, sample holdings.\nGuardian: labelled risk scenarios.']],label='BASELINE RESULT · 24–27 MIN',notes=cue('Embedded walkthrough step 1 → result','Click the baseline Run control. Read the summary, then expand the raw output if useful. Rebalancer: price, checkpoint, target and proposed change. Guardian: health factor, cap and whether it restores the target. No terminal typing.','A proposal is something we can inspect before granting action authority.','An actual browser execution result. No swap or repayment is claimed.','If the read fails, show the error and retry once or use Guardian.')),
's17':dict(title='Change one rule. Compare.',kind='two',content=[['Target allocation', 'Rebalancer: 50% → 70% SUI.\nCompare HOLD, BUY or SELL.'], ['Risk conditions', 'Guardian: at risk → healthy → unknown.\nCompare proposals and stop conditions.']],label='PARAMETERS → RESULTS · 27–31 MIN',drills=[],icons=[],arrows=False,notes=cue('Walkthrough change/compare → evidence','Use the next-step buttons to run the changed setting. Compare the saved baseline and new result. For Guardian, run the unknown-data case too. Then open the real Sui evidence link. Match the digest/status/balances/gas to the explorer; the historical Guardian receipt is a previous demo.','The rule changes a proposal. A chain receipt proves a separate executed action.','Both outputs remain visible for comparison. Unknown data stops Guardian.','Stay on the labelled scenario or previous receipt if the network fails; never fabricate a new transaction.')),
's18':dict(title='Save the evidence.',content=[['Decision record', 'Inputs, changed rule and outputs.\nKeep the supporting source.'], ['Cost + stop', 'Read-only run: no transaction fee.\nOne result, then completion.']],label='SAVE → STOP · 31–34 MIN',notes=cue('Walkthrough save step → Modify the agent (slide 21)','Click Save to download the comparison. Each run is one-shot. Explain that the optional coding-agent wrapper can have its normal model cost; this browser helper makes no model or signing call. Close the completed walkthrough and open Modify the agent (slide 21). Slide 20 is an optional decision-record summary, not another recipe selection.','That was our shared example. Now you will make your own change.','Saved evidence and a clear handoff to independent work.','If no successful result exists, save the error and next diagnostic step without calling it a success.')),
's19':dict(title='Keep the decision record.',content='Inputs → rule → result → evidence.\nSave the output and its source.',notes=cue('Decision-record summary → Modify the agent','Briefly summarize the saved inputs, changed rule, result and supporting evidence. Do not repeat recipe selection or show another QR. Advance to Modify the agent (slide 21) for the independent work at minute 34. If funding opened at 21:00 it closes at 36:00; the operator handles export separately.','You now have 17 minutes for your own experiment. Pick one change you can explain.','Everyone knows this is independent work, not another presenter demo.','Pair up or use Guardian scenarios if connectivity is poor.'), label='RESULTS + EVIDENCE'),
's20':dict(title='Modify the agent.',kind='two',content=[['Sui Rebalancer', 'Target: 50% → 70%. Band: 5% → 10%.\nCompare the proposed allocation.'], ['Liquidation Guardian', 'Target health factor: 1.3 → 1.5.\nCompare the capped response; test unknown data.']],label='PARAMETER EXPERIMENTS · 35–46 MIN',notes=cue('Participant builder pages','At 34:00 hand over to independent work on the recipe already open. Rebalancer: change target SUI from 50% to 70%, then the band from 5 to 10 percentage points. Guardian: change target health factor from 1.3 to 1.5, then test unknown data. Compare and save outputs. Do not repeat recipe selection. Optional local code is available for builders who want it.','Try one small change, compare the output, and prepare a short explanation.','A chosen setting and an output the participant can explain.','Use the browser route or work in pairs. Full funded swaps/repayments are outside this lesson unless separately rehearsed.')),
})

# Actual standalone deployment is the primary workshop path. The old browser
# helpers remain reachable only as explicitly labelled fallback exercises.
updates.update({
's12':dict(title='One job. A running agent.',kind='two',content=[['Sui Rebalancer','Read the wallet and market.\nMaintain a target SUI position.'],['A complete cycle','Observe → decide → quote → simulate.\nInspect the output. Stop the process.']],label='SUI REBALANCER',notes=cue('Slide → installed standalone runtime','Focus on Rebalancer. Guardian stays out of the main demonstration until separately accepted. The recipe uses price thresholds and a dollar target; it is not the old percentage-allocation browser exercise.','A useful agent has a real input, a decision and an observable result.','A named installed instance, actual wallet balances and current run output.','If the live route is not accepted, identify the precise blocker; do not present the old helper as a deployed agent.')),
's13':dict(title='From source to a running agent.',content=[['Prepare + configure','Node 24, public wallet, strategy.\nInstall the pinned recipe.'],['Run + inspect','Start the process. Read the logs.\nChange a rule. Stop the agent.']],label='DEPLOYMENT',notes=cue('Deck → local deployment console','Open the Studio deployment console through the local tunnel. Every operation has its own button and returns actual process output. Leave signing disabled until the exact funded action has been reviewed.','Each step produces evidence that the next step can use.','Actual runtime version, configuration, installation and process status.','The public download provides the same standalone source; AEX is not required.')),
's14':dict(title='Open the Rebalancer kit.',content=[['1 · Download','Get the standalone recipe and console.\nNode 24 is required.'],['2 · Launch','Unzip the kit. Follow the Mac or Windows steps.\nCopy the command to open the console.']],label='START THE BUILD · 20–23 MIN',notes=cue('Kit QR → deployment guide','Show the single Build QR. The guide provides the downloadable kit and platform-specific launch steps. Explain Node 24 once. Use Build QR first. In step 02, builders create or sign in to their own wallet, approve email, verify the address and save the strategy. Then return here, select Funding QR and open the 15-minute window. Never project the operator key.','The same source and controls run locally.','The local console is open, not just a downloaded file.','Pair up with a configured laptop if Node setup takes too long.')),
's15':dict(title='Check. Configure. Install.',kind='two',content=[['Runtime + wallet','Check Node and recipe version.\nSet a public Sui wallet address.'],['Strategy + installation','Set the SUI dollar target and price limits.\nInstall the pinned dependencies.']],label='DEPLOY THE RECIPE · 23–24 MIN',notes=cue('Deployment console: Prepare → Configure → Deploy','Click Prepare and verifyNode24/source. Review the public wallet and real balances; historical default wallet is empty and not signer-verified. Set price thresholds, SUI dollar target and cadence. Click Deploy; inspect npmci output. These are real installation/configuration operations.','Deployment makes the recipe executable; funding determines what it can do.','Pinned dependency installation exits successfully.','Any configuration or installation error stays visible and blocks the run.')),
's16':dict(title='Start the agent. Read the output.',kind='two',content=[['Observe','Fresh Sui checkpoint and pool price.\nActual wallet balances.'],['Decide','Hold, buy or sell under the configured rule.\nFunding errors remain visible.']],label='RUN · 24–27 MIN',notes=cue('Deployment console: Run once / Start','Click Run once first. Inspect the actualJSONL strategy output. Only start repeatedruns after the one-cycle outcome is understood. An unfundedwallet is a blockedrun, not a successfultrade.','The log shows what this process actually observed and decided.','Current timestamps, wallet, balance and strategy outcome.','Stop on failure; do not replace the wallet with sample holdings.')),
's17':dict(title='Inspect the proposed swap.',kind='two',content=[['Route + limits','Cetus quote, input amount and slippage.\nGas reserve and trade cap.'],['Transaction evidence','Unsigned build and Sui simulation.\nA receipt only after an approved send.']],label='INSPECT · 27–31 MIN',notes=cue('Deployment console: Inspect → raw output','Distinguish quote, unsigned transactionbuild, actualRPCsimulation and liveconfirmedreceipt. Currentdeployment has no signer; only claimstages whose outputexists. Fundingand exactsigningreview are still required before liveexecution.','A route is not a receipt. Each stage has its own result.','Amount, minimumoutput, simulationstatus and anyfailure.','Retain a failed or unfundedoutcome honestly; do not show historicalreceipts as a newrun.')),
's18':dict(title='Change one rule. Run again.',content=[['Change','Adjust a price limit or SUI dollar target.\nKeep the same wallet.'],['Compare','Run again against current chain data.\nExplain the changed decision.']],label='MODIFY · 31–34 MIN',notes=cue('Deployment console: Stop → Modify → Run once','Stop scheduledruns, changeonestrategyparameter and save. Run onceagain; compareactualoutputs. The samewalletandsource stayselected.','The change is visible in configuration and the next real run.','Bothrunrecords and causeofdecisionchange.','Ifcapital ismissing, recordthatblocker; do notchange tosimulatedfunds.')),
's19':dict(title='Stop. Keep the evidence.',content='Stop the process and its schedule.\nSave the inputs, run output and result.',label='STOP + SAVE',notes=cue('Deployment console: Stop → Download output','ClickStop and verifyrunning=false/nochildprocess. Save realJSONLoutput. Showthe independenttasknext.','Stopping is an observable operation.','Noactiveprocessorscheduledrun.','Force-stop only this isolated process if the gracefulstop timesout.')),
's20':dict(title='Modify the Rebalancer.',kind='two',content=[['Change one parameter','Move a price limit or the SUI dollar target.\nRun against the same wallet.'],['Explain the outcome','Compare price, balances and decision.\nSave the output. Stop the agent.']],label='INDEPENDENT BUILD · 34–51 MIN',notes=cue('Participant deployment consoles','Everyonecontinueswiththeinstalledrecipe. Changeoneparameter, runonce, explainandstop. No secondrecipeselection. GuardianfollowsonlyafterRebalancerisstable.','One change, one real run, one explanation.','Actualprocessoutput, not prewrittenresults.','Pairup iflocalsetupfailed.')),
})

base='https://holonym-foundation.github.io/basecamp-builder-lab/'
qr=base64.b64encode((ROOT/'assets/build-qr.png').read_bytes()).decode()
js='''<script>(()=>{
const base=BASE,defs={build:['Recipes + source ↗',base+'deploy.html'],library:['Starter sources ↗',base+'build.html#library'],guard:['Live Sui evidence ↗',base],hunt:['Non-chain Hunt ↗',base+'hunt.html'],receipt:['Previous pool receipt ↗',base+'?tx=Fvdxzog5tBYp3D4gg85PJxd6j4embkbcKyMKowhYnFV8'],guardian:['Previous Guardian demo ↗','https://suivision.xyz/txblock/4Fpevq1op4CiaQT79ZSvrQE8Jcc8reh8zvp5kjCPgiMG']};
const links={s12:['library'],s13:['build'],s14:[],s15:['build'],s16:['build'],s17:['receipt','guardian'],s18:['build'],s20:['build'],s23:['library'],s25:['hunt'],s26:['build','hunt'],s29:['build'],s30:['build','guard']};
function protect(a){a.target='_blank';a.rel='noopener noreferrer';for(const type of ['click','keydown'])a.addEventListener(type,e=>e.stopPropagation());}
for(const [id,keys]of Object.entries(links)){const nav=document.createElement('nav');nav.className='workshop-actions';nav.setAttribute('aria-label','Workshop links');for(const key of keys){const a=document.createElement('a');a.className='workshop-link';a.textContent=defs[key][0];a.href=defs[key][1];protect(a);nav.append(a);}document.querySelector('#slide-'+id)?.append(nav);}
for(const id of ['s14']){const box=document.createElement('div');box.className='workshop-qr';const a=document.createElement('a');a.href=base+'deploy.html';protect(a);const img=document.createElement('img');img.src='data:image/png;base64,QR';img.alt='Scan to get the standalone Rebalancer kit';a.append(img,document.createTextNode('Rebalancer deployment kit'));const p=document.createElement('p');p.textContent='Recipes + source + execution';box.append(a,p);const slide=document.querySelector('#slide-'+id);slide.append(box);const url=document.createElement('a');url.className='workshop-build-url';url.href=base+'deploy.html';url.textContent=url.href;url.style.cssText='position:absolute;left:128px;bottom:140px;font-size:29px;color:#2ed0bd;text-decoration:underline;text-underline-offset:6px';protect(url);slide.append(url);}
})();</script>'''.replace('BASE',json.dumps(base)).replace('QR',qr)
funding_config = ROOT/'funding-registration.json'
if funding_config.exists():
    registration = json.loads(funding_config.read_text())
    funding_qr = base64.b64encode((ROOT/'assets/funding-qr.png').read_bytes()).decode()
    js += '''<script>(()=>{
const form=FORM, fundingQR='data:image/png;base64,FUNDING_IMAGE';
for(const id of ['s14']){
 const slide=document.querySelector('#slide-'+id),box=slide.querySelector('.workshop-qr'),a=box.querySelector('a'),img=box.querySelector('img'),p=box.querySelector('p');
 const buildURL=a.href,buildQR=img.src;
 const controls=document.createElement('div');controls.style.cssText='display:flex;gap:12px;justify-content:center;margin-top:18px';
 for(const mode of ['Build QR','Funding QR']){
  const b=document.createElement('button');b.type='button';b.className='workshop-link secondary';b.style.cssText='font-size:21px;padding:10px 16px;cursor:pointer';b.textContent=mode;b.setAttribute('aria-pressed',String(mode==='Build QR'));
  for(const type of ['click','keydown'])b.addEventListener(type,e=>e.stopPropagation());
  b.addEventListener('click',()=>{const funding=mode==='Funding QR';a.href=funding?form:buildURL;const visibleURL=slide.querySelector('.workshop-build-url');visibleURL.href=a.href;visibleURL.textContent=a.href;img.src=funding?fundingQR:buildQR;img.alt=funding?'Scan to request workshop funding':'Scan to get the standalone Rebalancer kit';a.lastChild.textContent=funding?'Workshop funding':'Rebalancer deployment kit';p.textContent=funding?'15-minute window · 30 funded places':'Recipes + source + execution';controls.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));});controls.append(b);
 }
 box.append(controls);
}
})();</script>'''.replace('FORM',json.dumps(registration['url'])).replace('FUNDING_IMAGE',funding_qr)
js += '<script>' + (ROOT/'deck/deployment-controls.js').read_text() + '</script>'
for name in ['index.html','aex-v4.html']:
    path=ROOT/'deck'/name;p=path.read_text()
    match=re.search(r'window.SLIDES\s*=\s*(\[.*?\]);',p,re.S);slides=json.loads(match[1])
    slides=[s for s in slides if s['id'] not in {'s26','s27','s29','s30'}]
    for index,s in enumerate(slides,1):
        s['num']=index
        if s['id'] in updates:s.update(updates[s['id']])
    # Same participant route in both variants; AEX tour remains an optional presenter cue.
    p=p[:match.start(1)]+json.dumps(slides,ensure_ascii=False)+p[match.end(1):]
    start=p.find('<script>(()=>{\nconst base=')
    if start!=-1:p=p[:start]+js+'</body></html>\n'
    p=p.replace('grid-template-columns:1fr;gap:42px','grid-template-columns:1fr!important;gap:42px')
    if 'hashchange' not in p:
        p=p.replace('fit(); go(start, false);', "fit(); go(start, false);\naddEventListener('hashchange', () => { const i = fromHash(); if (i >= 0) { if (drill.open) closeDrill(); go(i, false); } });")
    p=re.sub(r'<title>.*?</title>','<title>Trade. Guard. Hunt. Claim. Build Agents That Do It All.</title>',p,flags=re.S)
    if '#slide-s19 .h{bottom:430px}' not in p:
        p=p.replace('#slide-s14 .card h3{font-size:46px}', '#slide-s19 .h{bottom:430px}#slide-s14 .card h3{font-size:46px}')
    p=p.replace('</head>','<style>#slide-s19 .h{bottom:430px}#slide-s14 .card h3{font-size:46px}#slide-s14 .card p{font-size:30px}#slide-s16 pre,#slide-s29 pre{font-size:34px}#slide-s12 .cols,#slide-s17 .cols,#slide-s20 .cols{bottom:265px}</style></head>') if '#slide-s14 .card h3' not in p else p
    path.write_text(p)
# Build the separate presenter companion after the audience slides.
import subprocess
subprocess.run(['python3',str(ROOT/'scripts/build-presenter-companion.py')],check=True)
